services:
  postgres:
    image: postgres:15-alpine
    container_name: private_notes_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: private_notes
    ports:
      - "5432:5432"
    volumes:
      - private_notes_data:/var/lib/postgresql/data

volumes:
    private_notes_data: